<section id="inner-headline">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<ul class="breadcrumb">
					<li><a href="#"><i class="fa fa-home"></i></a><i
						class="icon-angle-right"></i></li>
					<li class="active">Contato</li>
				</ul>
			</div>
		</div>
	</div>
</section>

<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<h2>
					Entre em contato <small>preenchendo o formulario abaixo</small>
				</h2>
				<hr class="colorgraph">
				<div id="sendmessage">Sua mensagem foi enviada. Obrigado!</div>
				<div id="errormessage"></div>
				<form action="" method="post" role="form" class="contactForm">
					<div class="form-group">
						<input type="text" name="name" class="form-control" id="name"
							placeholder="Seu nome" data-rule="minlen:4"
							data-msg="Por favor, insira pelo menos 4 caracteres" />
						<div class="validation"></div>
					</div>
					<div class="form-group">
						<input type="email" class="form-control" name="email" id="email"
							placeholder="Seu email" data-rule="email"
							data-msg="Por favor, adicione um email valido" />
						<div class="validation"></div>
					</div>
					<div class="form-group">
						<input type="text" class="form-control" name="subject" id="subject"
							placeholder="Assunto" data-rule="minlen:4"
							data-msg="Por favor, insira pelo menos 8 caracteres de assunto" />
						<div class="validation"></div>
					</div>
					<div class="form-group">
						<textarea class="form-control" name="message" rows="5"
							data-rule="required" data-msg="Por favor, escreva algo para nos"
							placeholder="Menssagem"></textarea>
						<div class="validation"></div>
					</div>
	
					<div class="text-center">
						<button type="submit" class="btn btn-theme btn-block btn-md">
							Enviar Mensagem
						</button>
					</div>
				</form>
				<hr class="colorgraph">
	
			</div>
		</div>
	</div>
</section>