<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description"
	content="Bootstrap 3 template for corporate business" />
<!-- css -->
<link href="css/bootstrap.min.css" rel="stylesheet" />
<link href="plugins/flexslider/flexslider.css" rel="stylesheet"
	media="screen" />
<link href="css/cubeportfolio.min.css" rel="stylesheet" />
<link href="css/style.css" rel="stylesheet" />

<!-- Theme skin -->
<link id="t-colors" href="skins/default.css" rel="stylesheet" />

<!-- boxed bg -->
<link id="bodybg" href="bodybg/bg1.css" rel="stylesheet" type="text/css" />

<!-- =======================================================
    Theme Name: Sailor
    Theme URL: https://bootstrapmade.com/sailor-free-bootstrap-theme/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
======================================================= -->

</head>



<!-- end header -->
<section id="featured" class="bg">
	<!-- start slider -->


	<!-- start slider -->
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<!-- Slider -->
				<div id="main-slider" class="main-slider flexslider">
					<ul class="slides">
						<li><img src="img/slides/flexslider/1.jpg" alt="" />
							<div class="flex-caption">
								<h3>Modern Design</h3>
								<p>Duis fermentum auctor ligula ac malesuada. Mauris et metus
									odio, in pulvinar urna</p>
								<a href="#" class="btn btn-theme">Learn More</a>
							</div></li>
						<li><img src="img/slides/flexslider/2.jpg" alt="" />
							<div class="flex-caption">
								<h3>Fully Responsive</h3>
								<p>Sodales neque vitae justo sollicitudin aliquet sit amet diam
									curabitur sed fermentum.</p>
								<a href="#" class="btn btn-theme">Learn More</a>
							</div></li>
						<li><img src="img/slides/flexslider/3.jpg" alt="" />
							<div class="flex-caption">
								<h3>Clean & Fast</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit donec
									mer lacinia.</p>
								<a href="#" class="btn btn-theme">Learn More</a>
							</div></li>
					</ul>
				</div>
				<!-- end slider -->
			</div>
		</div>
	</div>
</section>

<section class="callaction">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="cta-text">
					<h2>
						Awesome site template <span>corporate</span> business
					</h2>
					<p>Etiam adipiscing, justo quis feugiat.Suspendisse eu erat quam.
						Vivamus porttitor eros quis nisi lacinia sed interdum</p>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="cta-btn">
					<a href="#" class="btn btn-theme btn-lg">Grab it now <i
						class="fa fa-angle-right"></i></a>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="text-center">
					<h2>
						We use <span class="highlight">modern</span> infrastructure &
						technology
					</h2>
					<p>Lorem ipsum dolor sit amet, ne duis posse mei, ut cum vero
						nominati. Sed graece aeterno consectetuer te. Cu duo tota
						deleniti, vis ea fuisset nostrum. Meliore inciderint qui ne. Suas
						cotidieque vel ut ei eros perpetua qui. Ponderum lobortis
						reformidans</p>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="row">
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="box">
							<div class="aligncenter">
								<div class="icon">
									<i class="fa fa-desktop fa-5x"></i>
								</div>
								<h4>Fully responsive</h4>
							</div>
						</div>
					</div>
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="box">
							<div class="aligncenter">
								<div class="icon">
									<i class="fa fa-file-code-o fa-5x"></i>
								</div>
								<h4>Fully responsive</h4>
							</div>
						</div>
					</div>
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="box">
							<div class="aligncenter">
								<div class="icon">
									<i class="fa fa-paper-plane-o fa-5x"></i>
								</div>
								<h4>Fully responsive</h4>
							</div>
						</div>
					</div>
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="box">
							<div class="aligncenter">
								<div class="icon">
									<i class="fa fa-cubes fa-5x"></i>
								</div>
								<h4>Fully responsive</h4>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- divider -->
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="solidline"></div>
			</div>
		</div>
	</div>
	<!-- end divider -->


	<!-- parallax  -->


	<!-- divider -->
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="solidline"></div>
			</div>
		</div>
	</div>
	<!-- end divider -->

	<!-- clients -->
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-md-2 aligncenter client">
				<img alt="logo" src="img/clients/logo1.png" class="img-responsive" />
			</div>

			<div class="col-xs-6 col-md-2 aligncenter client">
				<img alt="logo" src="img/clients/logo2.png" class="img-responsive" />
			</div>

			<div class="col-xs-6 col-md-2 aligncenter client">
				<img alt="logo" src="img/clients/logo3.png" class="img-responsive" />
			</div>

			<div class="col-xs-6 col-md-2 aligncenter client">
				<img alt="logo" src="img/clients/logo4.png" class="img-responsive" />
			</div>

			<div class="col-xs-6 col-md-2 aligncenter client">
				<img alt="logo" src="img/clients/logo5.png" class="img-responsive" />
			</div>
			<div class="col-xs-6 col-md-2 aligncenter client">
				<img alt="logo" src="img/clients/logo6.png" class="img-responsive" />
			</div>

		</div>
	</div>

</section>


<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>

<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery.min.js"></script>
<script src="js/modernizr.custom.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="plugins/flexslider/jquery.flexslider-min.js"></script>
<script src="plugins/flexslider/flexslider.config.js"></script>
<script src="js/jquery.appear.js"></script>
<script src="js/stellar.js"></script>
<script src="js/classie.js"></script>
<script src="js/uisearch.js"></script>
<script src="js/jquery.cubeportfolio.min.js"></script>
<script src="js/google-code-prettify/prettify.js"></script>
<script src="js/animate.js"></script>
<script src="js/custom.js"></script>