<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="Bootstrap 3 template for corporate business" />

<!-- css -->
<link href="css/bootstrap.min.css" rel="stylesheet" />
<link href="plugins/flexslider/flexslider.css" rel="stylesheet" media="screen" />
<link href="css/cubeportfolio.min.css" rel="stylesheet" />
<link href="css/style.css" rel="stylesheet" />

<!-- Theme skin -->
<link id="t-colors" href="skins/default.css" rel="stylesheet" />

<!-- boxed bg -->
<link id="bodybg" href="bodybg/bg1.css" rel="stylesheet" type="text/css" />

</head>

<section class="callaction">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="cta-text">
					<h2>
						Awesome site template <span>corporate</span> business
					</h2>
					<p>
						Etiam adipiscing, justo quis feugiat.Suspendisse eu erat quam.
						Vivamus porttitor eros quis nisi lacinia sed interdum
					</p>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="cta-btn">
					<a href="#" class="btn btn-theme btn-lg">Grab it now <i
						class="fa fa-angle-right"></i></a>
				</div>
			</div>
		</div>
	</div>
</section>

<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>

<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery.min.js"></script>
<script src="js/modernizr.custom.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="plugins/flexslider/jquery.flexslider-min.js"></script>
<script src="plugins/flexslider/flexslider.config.js"></script>
<script src="js/jquery.appear.js"></script>
<script src="js/stellar.js"></script>
<script src="js/classie.js"></script>
<script src="js/uisearch.js"></script>
<script src="js/jquery.cubeportfolio.min.js"></script>
<script src="js/google-code-prettify/prettify.js"></script>
<script src="js/animate.js"></script>
<script src="js/custom.js"></script>