<section id="inner-headline">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<ul class="breadcrumb">
					<li><a href="#"><i class="fa fa-home"></i></a><i
						class="icon-angle-right"></i></li>
					<li class="active">Newsletter</li>
				</ul>
			</div>
		</div>
	</div>
</section>

<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<h2>
					<?php echo $this->view->teste ?>
				</h2>
				
				<?php echo $this->view->form->gerarForm();?>
				
			</div>
		</div>
	</div>
</section>